package com.libra.streaming.media.processing.infrastructure;

import com.libra.streaming.media.processing.application.MediaProber;
import com.libra.streaming.media.processing.application.SourcePolicy;
import com.libra.streaming.media.processing.domain.ProcessingFailure;
import com.libra.streaming.media.processing.domain.SourceMetadata;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.assertj.core.api.Assertions.*;

/**
 * The real ffprobe against synthetic fixtures generated by {@link MediaFixtures}. Nothing is mocked: the tool,
 * the JSON it prints, the reader and the policy all run. The executable comes from LIBRA_FFPROBE_PATH or PATH; a
 * missing tool fails the build, like a missing Docker daemon, instead of silently skipping the evidence.
 */
class FfprobeFixtureIntegrationTest {
    private static FfprobeMediaProber prober;
    private static String version;
    @TempDir Path scratch;

    @BeforeAll
    static void locateTool() throws Exception {
        var executable = FfprobeLocator.locate();
        prober = new FfprobeMediaProber(executable, Duration.ofSeconds(30), 262144);
        version = prober.version();
        assertThat(version).startsWith("ffprobe version");
        System.out.println("FFPROBE_EVIDENCE " + executable.getFileName() + " :: " + version);
    }

    private Path fixture(String name) throws IOException {
        var target = scratch.resolve(name);
        Files.copy(MediaFixtures.file(name), target, StandardCopyOption.REPLACE_EXISTING);
        return target;
    }

    private SourcePolicy.Verdict verdict(String name) throws Exception {
        return SourcePolicy.evaluate(prober.probe(fixture(name), () -> false));
    }

    private SourceMetadata accepted(String name) throws Exception {
        var verdict = verdict(name);
        assertThat(verdict).as(name).isInstanceOf(SourcePolicy.Verdict.Accepted.class);
        return ((SourcePolicy.Verdict.Accepted) verdict).metadata();
    }

    private void rejected(String name, ProcessingFailure failure, SourcePolicy.Reason reason) throws Exception {
        assertThat(verdict(name)).as(name).isEqualTo(new SourcePolicy.Verdict.Rejected(failure, reason));
    }

    @Test
    void highResolutionSourceWithAacIsAccepted() throws Exception {
        var metadata = accepted("valid-1080p-aac.mp4");
        assertThat(metadata.codedWidth()).isEqualTo(1920);
        assertThat(metadata.codedHeight()).isEqualTo(1080);
        assertThat(metadata.displayWidth()).isEqualTo(1920);
        assertThat(metadata.rotation()).isZero();
        assertThat(metadata.frameRateNumerator()).isEqualTo(30);
        assertThat(metadata.frameRateDenominator()).isEqualTo(1);
        assertThat(metadata.videoProfile()).isEqualTo("High");
        assertThat(metadata.audio()).isEqualTo(new SourceMetadata.Audio(2, 48000));
        assertThat(metadata.durationMillis()).isBetween(900L, 1200L);
    }

    @Test
    void lowResolutionSilentSourceIsAcceptedAndStaysSilent() throws Exception {
        var metadata = accepted("valid-160x96-silent.mp4");
        assertThat(metadata.displayWidth()).isEqualTo(160);
        assertThat(metadata.displayHeight()).isEqualTo(96);
        assertThat(metadata.hasAudio()).isFalse();
        assertThat(metadata.frameRateNumerator()).isEqualTo(15);
        assertThat(metadata.durationMillis()).isBetween(1900L, 2300L);
    }

    @Test
    void rotationMetadataIsNormalizedIntoDisplayDimensions() throws Exception {
        var metadata = accepted("valid-rotated-90.mp4");
        assertThat(metadata.codedWidth()).isEqualTo(1280);
        assertThat(metadata.codedHeight()).isEqualTo(720);
        assertThat(metadata.rotation()).isIn(90, 270);
        assertThat(metadata.displayWidth()).isEqualTo(720);
        assertThat(metadata.displayHeight()).isEqualTo(1280);
        assertThat(metadata.hasAudio()).isTrue();
    }

    @Test
    void anamorphicPixelsAreSquaredIntoTheDisplayWidth() throws Exception {
        var metadata = accepted("valid-anamorphic.mp4");
        assertThat(metadata.codedWidth()).isEqualTo(1440);
        assertThat(metadata.displayWidth()).isEqualTo(1920);
        assertThat(metadata.displayHeight()).isEqualTo(1080);
    }

    @Test
    void ntscFrameRateKeepsItsExactFraction() throws Exception {
        var metadata = accepted("valid-ntsc-rate.mp4");
        assertThat(metadata.frameRateNumerator()).isEqualTo(30000);
        assertThat(metadata.frameRateDenominator()).isEqualTo(1001);
    }

    @Test
    void theLongestAcceptedClipIsTenMinutes() throws Exception {
        assertThat(accepted("valid-600s.mp4").durationMillis()).isBetween(599_000L, 600_000L);
        rejected("invalid-601s.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.DURATION_RANGE);
    }

    @Test
    void unsupportedCodecsFormatsAndStreamsAreRejectedPermanently() throws Exception {
        rejected("invalid-hevc.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.VIDEO_CODEC);
        rejected("invalid-10bit.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.VIDEO_PROFILE);
        rejected("invalid-hdr.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.HDR);
        rejected("invalid-4k.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.RESOLUTION);
        rejected("invalid-60fps.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.FRAME_RATE_RANGE);
        rejected("invalid-two-audio.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.EXTRA_AUDIO);
        rejected("invalid-mp3-audio.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.AUDIO_CODEC);
        rejected("invalid-container.mkv", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.NOT_MP4);
        rejected("invalid-cover-art.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.STREAM_KIND);
        rejected("invalid-subtitle.mp4", ProcessingFailure.UNSUPPORTED_MEDIA, SourcePolicy.Reason.STREAM_KIND);
    }

    @Test
    void corruptOrNonMediaInputIsAPermanentFailureNotAToolFault() throws Exception {
        for (String name : new String[] {"corrupt-truncated.mp4", "corrupt-garbage.bin"}) {
            assertThatThrownBy(() -> prober.probe(fixture(name), () -> false)).as(name)
                    .isInstanceOf(MediaProber.Unreadable.class);
        }
    }

    @Test
    void aContainerCannotPointTheToolAtAnotherFileOrAnUrl() throws Exception {
        // Only the file protocol is whitelisted, so a reference to a remote or local resource cannot be followed.
        var playlist = scratch.resolve("reference.m3u8");
        Files.writeString(playlist, "#EXTM3U\n#EXTINF:1,\nhttp://127.0.0.1:9/never.mp4\n#EXT-X-ENDLIST\n");
        assertThatThrownBy(() -> prober.probe(playlist, () -> false)).isInstanceOf(MediaProber.Unreadable.class);
        var concat = scratch.resolve("reference.ffconcat");
        Files.writeString(concat, "ffconcat version 1.0\nfile '" + fixture("valid-160x96-silent.mp4").toString()
                .replace("\\", "/") + "'\n");
        assertThatThrownBy(() -> prober.probe(concat, () -> false)).isInstanceOf(MediaProber.Unreadable.class);
    }

    @Test
    void theFileNameCannotChangeTheMeaningOfTheCommand() throws Exception {
        var odd = scratch.resolve("-i http;&echo x $(y) 'z'.mp4");
        try {
            Files.copy(fixture("valid-160x96-silent.mp4"), odd);
        } catch (java.nio.file.InvalidPathException | IOException unsupportedName) {
            odd = scratch.resolve("-version spaces & quotes.mp4");
            Files.copy(fixture("valid-160x96-silent.mp4"), odd);
        }
        var metadata = ((SourcePolicy.Verdict.Accepted) SourcePolicy.evaluate(prober.probe(odd, () -> false))).metadata();
        assertThat(metadata.displayWidth()).isEqualTo(160);
    }
}
